### ISSUE TITLE
Private Mode on Firefox for Windows Doesn't work properly

### ISSUE THREAD

**Issue by AlexVCS** [grammerhub/grammerhub.github.io#7]
Look at this screenshot of the page on Firefox private mode for Windows. It doesn't always load this way but for some users it looks off like this. Please try and find the source of the problem and fix it.

![IMG_0636](https://user-images.githubusercontent.com/49458917/148479052-1ba7a369-a9c5-4bf6-b80c-7c6f3aed7db3.jpg)

**Comment by AlexVCS** [comment]
Different browsers behave differently here so please try and test this across multiple browsers.

**Comment by ssmodish** [comment]
Solved HTTPS issue
